### ISSUE TITLE
vcpkg port version mismatch

### ISSUE THREAD

**Issue by ThirdEyeSqueegee** [Starfield-Reverse-Engineering/Starfield-RE-vcpkg#7]
https://github.com/Starfield-Reverse-Engineering/Starfield-RE-vcpkg/blob/05d3fdf03efb38b9c7e8440b0040670f0c4ba6b3/ports/commonlibsf/vcpkg.json#L4
This needs to be updated in the workflow along with the other version entries

**Comment by gottyduke** [comment]
Tested of working with current ci sync workflow, as of `2023-09-10.1`
